config/routes.rb
Rails.application.routes.draw do
  resources :company_dei_fields do
    delete 'toggle_off'
  end
  resources :dei_field_answers
  resources :dei_fields
  resources :dei_categories
  resources :companies do
    get 'toggle_on'
  end
  get 'profile', to: 'users#profile', as: :profile
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dei_field_answer.rb
class DeiFieldAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :dei_field
end

app/controllers/dei_field_answers_controller.rb
class DeiFieldAnswersController < ApplicationController
  before_action :set_dei_field_answer, only: %i[ show edit update destroy ]

  # GET /dei_field_answers or /dei_field_answers.json
  def index
    @dei_field_answers = DeiFieldAnswer.all
  end

  # GET /dei_field_answers/1 or /dei_field_answers/1.json
  def show
  end

  # GET /dei_field_answers/new
  def new
    @dei_field_answer = DeiFieldAnswer.new
  end

  # GET /dei_field_answers/1/edit
  def edit
  end

  # POST /dei_field_answers or /dei_field_answers.json
  def create
    @dei_field_answer = DeiFieldAnswer.new(dei_field_answer_params)
    @dei_field_answer.user = current_user

      if @dei_field_answer.save
        redirect_to profile_path
      else

      end

  end

  # PATCH/PUT /dei_field_answers/1 or /dei_field_answers/1.json
  def update
    respond_to do |format|
      if @dei_field_answer.update(dei_field_answer_params)
        format.html { redirect_to @dei_field_answer, notice: "Dei field answer was successfully updated." }
        format.json { render :show, status: :ok, location: @dei_field_answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dei_field_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dei_field_answers/1 or /dei_field_answers/1.json
  def destroy
    @dei_field_answer.destroy
    respond_to do |format|
      format.html { redirect_to dei_field_answers_url, notice: "Dei field answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dei_field_answer
      @dei_field_answer = DeiFieldAnswer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dei_field_answer_params
      params.require(:dei_field_answer).permit(:user_id, :dei_field_id, :encrypted_answer, :encrypted_answer_iv)
    end
end

app/views/dei_field_answers/_form.html.erb
<%= simple_form_for(@dei_field_answer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :dei_field %>
    <%= f.input :encrypted_answer %>
    <%= f.input :encrypted_answer_iv %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dei_field_answers/edit.html.erb
<h1>Editing Dei Field Answer</h1>

<%= render 'form', dei_field_answer: @dei_field_answer %>

<%= link_to 'Show', @dei_field_answer %> |
<%= link_to 'Back', dei_field_answers_path %>

app/views/dei_field_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dei Field Answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Dei field</th>
      <th>Encrypted answer</th>
      <th>Encrypted answer iv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dei_field_answers.each do |dei_field_answer| %>
      <tr>
        <td><%= dei_field_answer.user_id %></td>
        <td><%= dei_field_answer.dei_field_id %></td>
        <td><%= dei_field_answer.encrypted_answer %></td>
        <td><%= dei_field_answer.encrypted_answer_iv %></td>
        <td><%= link_to 'Show', dei_field_answer %></td>
        <td><%= link_to 'Edit', edit_dei_field_answer_path(dei_field_answer) %></td>
        <td><%= link_to 'Destroy', dei_field_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dei Field Answer', new_dei_field_answer_path %>

app/views/dei_field_answers/new.html.erb
<h1>New Dei Field Answer</h1>

<%= render 'form', dei_field_answer: @dei_field_answer %>

<%= link_to 'Back', dei_field_answers_path %>

app/views/dei_field_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @dei_field_answer.user_id %>
</p>

<p>
  <strong>Dei field:</strong>
  <%= @dei_field_answer.dei_field_id %>
</p>

<p>
  <strong>Encrypted answer:</strong>
  <%= @dei_field_answer.encrypted_answer %>
</p>

<p>
  <strong>Encrypted answer iv:</strong>
  <%= @dei_field_answer.encrypted_answer_iv %>
</p>

<%= link_to 'Edit', edit_dei_field_answer_path(@dei_field_answer) %> |
<%= link_to 'Back', dei_field_answers_path %>