config/routes.rb
Rails.application.routes.draw do
  resources :company_dei_fields do
    delete 'toggle_off'
  end
  resources :dei_field_answers
  resources :dei_fields
  resources :dei_categories
  resources :companies do
    get 'toggle_on'
  end
  get 'profile', to: 'users#profile', as: :profile
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company_dei_field.rb
class CompanyDeiField < ApplicationRecord
  belongs_to :company
  belongs_to :dei_field
end

app/controllers/company_dei_fields_controller.rb
class CompanyDeiFieldsController < ApplicationController
  before_action :set_company_dei_field, only: %i[ show edit update destroy ]

  # GET /company_dei_fields or /company_dei_fields.json
  def index
    @company_dei_fields = CompanyDeiField.all
  end

  # GET /company_dei_fields/1 or /company_dei_fields/1.json
  def show
  end

  def toggle_off
    cdf = CompanyDeiField.find(params[:company_dei_field_id])
    company = cdf.company
    cdf.destroy
    redirect_to company_path(company)
  end

  # GET /company_dei_fields/new
  def new
    @company_dei_field = CompanyDeiField.new
  end

  # GET /company_dei_fields/1/edit
  def edit
  end

  # POST /company_dei_fields or /company_dei_fields.json
  def create
    @company_dei_field = CompanyDeiField.new(company_dei_field_params)

    respond_to do |format|
      if @company_dei_field.save
        format.html { redirect_to @company_dei_field, notice: "Company dei field was successfully created." }
        format.json { render :show, status: :created, location: @company_dei_field }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company_dei_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_dei_fields/1 or /company_dei_fields/1.json
  def update
    respond_to do |format|
      if @company_dei_field.update(company_dei_field_params)
        format.html { redirect_to @company_dei_field, notice: "Company dei field was successfully updated." }
        format.json { render :show, status: :ok, location: @company_dei_field }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company_dei_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_dei_fields/1 or /company_dei_fields/1.json
  def destroy
    @company_dei_field.destroy
    respond_to do |format|
      format.html { redirect_to company_dei_fields_url, notice: "Company dei field was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_dei_field
      @company_dei_field = CompanyDeiField.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_dei_field_params
      params.require(:company_dei_field).permit(:company_id, :dei_field_id)
    end
end

app/views/company_dei_fields/_form.html.erb
<%= simple_form_for(@company_dei_field) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :company %>
    <%= f.association :dei_field %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/company_dei_fields/edit.html.erb
<h1>Editing Company Dei Field</h1>

<%= render 'form', company_dei_field: @company_dei_field %>

<%= link_to 'Show', @company_dei_field %> |
<%= link_to 'Back', company_dei_fields_path %>

app/views/company_dei_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Dei Fields</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Dei field</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_dei_fields.each do |company_dei_field| %>
      <tr>
        <td><%= company_dei_field.company_id %></td>
        <td><%= company_dei_field.dei_field_id %></td>
        <td><%= link_to 'Show', company_dei_field %></td>
        <td><%= link_to 'Edit', edit_company_dei_field_path(company_dei_field) %></td>
        <td><%= link_to 'Destroy', company_dei_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Dei Field', new_company_dei_field_path %>

app/views/company_dei_fields/new.html.erb
<h1>New Company Dei Field</h1>

<%= render 'form', company_dei_field: @company_dei_field %>

<%= link_to 'Back', company_dei_fields_path %>

app/views/company_dei_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @company_dei_field.company_id %>
</p>

<p>
  <strong>Dei field:</strong>
  <%= @company_dei_field.dei_field_id %>
</p>

<%= link_to 'Edit', edit_company_dei_field_path(@company_dei_field) %> |
<%= link_to 'Back', company_dei_fields_path %>