config/routes.rb
Rails.application.routes.draw do
  resources :company_dei_fields do
    delete 'toggle_off'
  end
  resources :dei_field_answers
  resources :dei_fields
  resources :dei_categories
  resources :companies do
    get 'toggle_on'
  end
  get 'profile', to: 'users#profile', as: :profile
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dei_category.rb
class DeiCategory < ApplicationRecord

  has_many :dei_fields
  has_many :dei_field_answers, through: :dei_fields
end

app/controllers/dei_categories_controller.rb
class DeiCategoriesController < ApplicationController
  before_action :set_dei_category, only: %i[ show edit update destroy ]

  # GET /dei_categories or /dei_categories.json
  def index
    @dei_categories = DeiCategory.all
  end

  # GET /dei_categories/1 or /dei_categories/1.json
  def show
  end

  # GET /dei_categories/new
  def new
    @dei_category = DeiCategory.new
  end

  # GET /dei_categories/1/edit
  def edit
  end

  # POST /dei_categories or /dei_categories.json
  def create
    @dei_category = DeiCategory.new(dei_category_params)

    respond_to do |format|
      if @dei_category.save
        format.html { redirect_to @dei_category, notice: "Dei category was successfully created." }
        format.json { render :show, status: :created, location: @dei_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dei_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dei_categories/1 or /dei_categories/1.json
  def update
    respond_to do |format|
      if @dei_category.update(dei_category_params)
        format.html { redirect_to @dei_category, notice: "Dei category was successfully updated." }
        format.json { render :show, status: :ok, location: @dei_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dei_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dei_categories/1 or /dei_categories/1.json
  def destroy
    @dei_category.destroy
    respond_to do |format|
      format.html { redirect_to dei_categories_url, notice: "Dei category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dei_category
      @dei_category = DeiCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dei_category_params
      params.require(:dei_category).permit(:name)
    end
end

app/views/dei_categories/_form.html.erb
<%= simple_form_for(@dei_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dei_categories/edit.html.erb
<h1>Editing Dei Category</h1>

<%= render 'form', dei_category: @dei_category %>

<%= link_to 'Show', @dei_category %> |
<%= link_to 'Back', dei_categories_path %>

app/views/dei_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dei Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dei_categories.each do |dei_category| %>
      <tr>
        <td><%= dei_category.name %></td>
        <td><%= link_to 'Show', dei_category %></td>
        <td><%= link_to 'Edit', edit_dei_category_path(dei_category) %></td>
        <td><%= link_to 'Destroy', dei_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dei Category', new_dei_category_path %>

app/views/dei_categories/new.html.erb
<h1>New Dei Category</h1>

<%= render 'form', dei_category: @dei_category %>

<%= link_to 'Back', dei_categories_path %>

app/views/dei_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dei_category.name %>
</p>

<%= link_to 'Edit', edit_dei_category_path(@dei_category) %> |
<%= link_to 'Back', dei_categories_path %>